version: '25082024'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./objects:/objects
      - ./structure:/structure
      - ./structure/DATAUSERS.csv:/DATAUSERS.csv
      - ./${BACKUP_DIR}:/${BACKUP_DIR}
    ports:
      - "3306:3306"
